###########
# site.title

title:    'Lava Avoiding Reward Searcher (LARS)'
subtitle: 'CS 175: Project in AI (in Minecraft)'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md

theme: jekyll-theme-cayman